# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 371fa0b1d8ec38ab9fa418fe29bba5d3a3da30fa05f2e8746055a48d25ba5fae70f96cc09149ebd805a44e6b2a6aaed39ff34a3b1a91027060926861ee27c9a7

test:
  secret_key_base: c53546b269f595aa43a09e9b31177d2896d86ec767c62435ffe0e1b1883507c60f1778625940b6e06c58c6568756b5adb45c0906bfef0a29b7700d00e15e2409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
